import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Body from "@/components/body";
import ModuleHeader from "@/components/moduleheader";
import { Footer } from "@/components/footer";
import { useEffect, useState } from "react";
import { AiOutlineLoading3Quarters } from "react-icons/ai";

export default function Home() {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    setTimeout(() => {
      setLoading(false);
    }, 1000);
  }, []);

  if (loading)
    return (
      <div className="text-center mx-0 h-screen flex items-center  justify-center">
        <div className="flex items-center text-white justify-center flex-col">
          <p className="dashboard-mssg"></p>
          <AiOutlineLoading3Quarters className="text-4xl animate-spin" />
        </div>
      </div>
    );

  return (
    <div className="">
      <Head>
        <title>Druminant - Home</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/image/mobilelogo.png"
        />
      </Head>
      <div className="main">
        <ModuleHeader />

        <Body />

        <div className="mt-60 md:mt-80">
          <Footer />
        </div>
      </div>
    </div>
  );
}
