import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Header from "@/components/header";
import Body from "@/components/body";
import ModuleHeader from "@/components/moduleheader";
import { Footer } from "@/components/footer";





const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  
  
 
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="main     ">
        <ModuleHeader />

        <Body />

        <div className="mt-20 md:mt-48">
          <Footer />
        </div>
      </div>
    </div>
  );
}
