import { userState } from "@/atom";
import { Footer } from "@/components/footer";
import ModuleHeader from "@/components/moduleheader";
import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/router";
import { useEffect } from "react";
import { FaUser } from "react-icons/fa";
import { toast } from "react-toastify";
import { useRecoilState } from "recoil";

function Profile() {
  const router = useRouter();
  const [userFromLocalStorage, setUserFromLocalStorage] =
    useRecoilState(userState);
  useEffect(() => {
    const user = localStorage.getItem("user");
    if (user) {
      const parsedUser = JSON.parse(user);
      setUserFromLocalStorage(parsedUser);
    }
  }, []);
  const currentPath = router.asPath;
  function logOut() {
    confirm("Are you sure you want to log out?")
    localStorage.removeItem("user");
    setUserFromLocalStorage(null);
    router.push("/");
    toast("Bye!");
    currentPath === "/" || currentPath === "/login" || currentPath === "/signup"
      ? "bg-transparent"
      : "";
    currentPath !== "/" && currentPath !== "/login" && currentPath !== "/signup"
      ? "#008000"
      : "transparent";
  }

  return (
    <div className="dashboard-main text-white">
      <Head>
        <title>Druminant - Profile</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/png" sizes="16x16" href="/image/mobilelogo.png" />
      </Head>
      <ModuleHeader />

      {userFromLocalStorage === null ? (
        <div className="text-center mx-0 h-screen flex items-center  justify-center">
          <div className="flex items-center text-white justify-center flex-col">
            <p className="dashboard-mssg">
              You are not logged in! <br />
              Please, log in to access profile
            </p>
            <Link href={"/login"} className="mss-login">
              login
            </Link>
          </div>
        </div>
      ) : (
       
        <div class="max-w-lg mx-auto  my-10 md:my-20  rounded-lg shadow-md p-5">
           <h1 className=" text-white -mt-10 text-center mb-16 md:mt-0" style={{ fontFamily: "verdana", fontWeight: "bold", fontSize: "20px" }}>User Profile</h1>
          {/* <Image class="w-32 h-32 rounded-full mx-auto" width={100} height={100} src="https://picsum.photos/200" alt="Profile picture"/> */}
          <FaUser class="w-32 h-32 text-[white] mt-8 rounded-full mx-auto" />
          <h2 class="text-center text-2xl font-semibold mt-3">@Samuel</h2>
          <p class="text-center text-gray-200 mt-1">awunor@gmail.com</p>
          <div className="text-center mt-16 flex  flex-col sm:flex-row justify-between">
            <Link href={"/dashboard"}>
              <p className="bg-[#008000] py-3 px-3 rounded mb-5 md:mb-0">Go to farm</p>
            </Link>
            <p className="bg-[#221c7a] py-3 cursor-pointer px-3 rounded mb-5  md:mb-0">Update profile</p>
            <p onClick={logOut} className="bg-[red] cursor-pointer py-3 px-3 rounded mb-5  md:mb-0">Log out</p>
          </div>


        </div>
      )}

      <div className="mt-28 md:mt-96">
        <Footer />
      </div>



    </div>
  );
}

export default Profile;
